apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260607-004618-sezxu6zr9sz4-service
spec:
  selector:
    app: enterprise-system-20260607-004618-sezxu6zr9sz4
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
